name: podcast_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.3.2
  flutter_screenutil: ^5.9.3
  asset_cache: ^2.1.0
  cached_network_image: ^3.4.1
  country_code_picker: ^2.0.2
  pinput: ^5.0.0
  carousel_slider: ^5.0.0
  image_picker: ^1.1.2
  syncfusion_flutter_gauges: ^27.1.53
  path_provider: ^2.1.4
  audio_waveforms: ^1.1.0
  fluttertoast: ^8.2.8

  collection: any
  universal_platform: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
